version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      args:
        UID: 1000
        GID: 1000
    container_name: filament-app
    volumes:
      - ./src:/var/www/html
    networks:
      - filament-net

  nginx:
    image: nginx:latest
    container_name: filament-nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - filament-net

  mysql:
    image: mysql:8.0
    container_name: filament-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: filament
      MYSQL_USER: filament
      MYSQL_PASSWORD: filament
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - filament-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: filament-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - filament-net

networks:
  filament-net:

volumes:
  db_data:
